### ISSUE TITLE
Flatten www folder into root of the repository

### ISSUE THREAD

**Issue by itsananderson** [wp-app/wp-app#3]
Setting up the project from scratch is a little bit complicated at the moment, if you want to keep the www folder under source control.

If you just try to `git clone` the repository into a folder created using `ionic start`, Git complains because the folder isn't an empty directory:

```
$ git clone git@github.com:wp-app/wp-app.git wp-app
fatal: destination path 'wp-app' already exists and is not an empty directory.
```

Instead, you have to do a multiple-step process:

```
cd wp-app
rm -rf www
git init
git remote add origin git@github.com:wp-app/wp-app.git
git fetch
git checkout master
```

This also leaves a bunch of "untracked" files, because the repository has no `.gitignore` checked in, so the following files show up when you run "git status".

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .bowerrc
        .editorconfig
        .gitignore
        bower.json
        config.xml
        gulpfile.js
        hooks/
        ionic.project
        package.json
        resources/
        scss/
```

It would certainly be possible to update the documentation to include those steps, but it would be nice if we could just update the project structure so that the repository could be cloned directly over the `www` folder. That way the steps would be:

```
cd wp-app
rm -rf www
git clone git@github.com:wp-app/wp-app.git www
```

This change would also make it possible to have a full Cordova project that simply takes `wp-app/wp-app.git` as a Git submodule. This would make it so people could still download just the web assets as a zip, but allow us to track the entire Cordova project in Git so mobile-friendly developers can pull down everything at once.
### Steps for implementing this change
1. Move screen mockup to S3 or some other external storage.
   As I understand, we could even hotlink it directly from the uploaded file that's created when I paste it into this issue... here 
   ![image](https://cloud.githubusercontent.com/assets/516559/9420253/3f53a01c-4818-11e5-96a3-d3713c7df3f7.png)
2. Move all files in the `www` folder into the root of the project
3. Delete the `www` folder (Git will automatically do this anyway if the folder contains no files)

If this is something we agree on, I'm happy to submit a PR, but it makes sense to hash out the details before I submit a big rename.

**Comment by scottopolis** [comment]
My only issue with this is if someone wants to download the project as a zip file, when they unzip it will need to be in a manually created folder. It's a minor issue, we'd just want to make sure it's documented.

Other than that I'd love to see a pull request.

**Comment by itsananderson** [comment]
I just tried downloading from the GitHub UI, and it already nests everything in a `<repo-name>-<branch-name>` folder inside the zip, so they shouldn't need to create a folder, though they may need to rename that folder to `www`.

I'll submit a PR later today.
