### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by itsananderson** [wp-app/wp-app#7]
Having seen the 5 month process that was required for [VVV to get all contributors to sign-off on a license](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/346), it might make sense to choose one now, while there's a relatively small contributor list.

I'm personally a fan of MIT and Apache because they're more permissive about distribution of derivative works, but GPL would also be a reasonable choice. http://choosealicense.com/

Thoughts?

**Comment by scottopolis** [comment]
Ionic is MIT, and WordPress is GPL. I don't really care personally, but the bulk of this code is Ionic so I kind of think we should use their license.

**Comment by itsananderson** [comment]
Sounds good. Since @danielmilner has contributed code, it'd be good to get him to sign off as well.

**Comment by danielmilner** [comment]
MIT sounds good to me.

**Comment by scottopolis** [comment]
MIT it is. I suppose we should wait for a commit to close this issue.
